---
# All rights reserved (c) 2020-2021, Vladimir Botka <vbotka@gmail.com>
# Simplified BSD License, https://opensource.org/licenses/BSD-2-Clause

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# ansible_lib: al_include_os_vars_playbook_dir
#
# Description: Include OS specific variables from playbook_dir
#
# Input: none
#
# Output: none
#
# Example:
#
#   tasks:
#     - include_role:
#         name: vbotka.ansible_lib
#         tasks_from: al_include_os_vars_playbook_dir.yml
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# https://github.com/vbotka/ansible-lib/blob/master/tasks/al_include_os_vars_playbook_dir.yml

# Defaults variables - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
- name: "al_include_os_vars_playbook_dir: Vars from {{ playbook_dir }}/vars/defaults"
  include_vars: "{{ _file }}"
  vars:
    _file: "{{ lookup('ansible.builtin.first_found', params) }}"
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - default.yml
        - defaults.yml
      paths: "{{ playbook_dir }}/vars/defaults"
      skip: true
  when: _file|length > 0

# Custom variables - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
- name: "al_include_os_vars_playbook_dir: Vars from {{ playbook_dir }}/vars"
  include_vars: "{{ _file }}"
  vars:
    _file: "{{ lookup('ansible.builtin.first_found', params) }}"
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - default.yml
        - defaults.yml
      paths: "{{ playbook_dir }}/vars"
      skip: true
  when: _file|length > 0

# EOF
...
