---
# All rights reserved (c) 2020, Vladimir Botka <vbotka@gmail.com>
# Simplified BSD License, https://opensource.org/licenses/BSD-2-Clause

- name: "Ansible lib Debug"
  vars:
    msg: |
      ansible_architecture [ {{ ansible_architecture }} ]
      ansible_os_family [ {{ ansible_os_family }} ]
      ansible_distribution [ {{ ansible_distribution }} ]
      ansible_distribution_major_version [ {{ ansible_distribution_major_version }} ]
      ansible_distribution_version [ {{ ansible_distribution_version }} ]
      ansible_distribution_release [ {{ ansible_distribution_release }} ]
      ansible_python_version [{{ ansible_python_version }}]

  debug:
    msg: "{{ msg.split('\n') }}"

# EOF
...
